version: '3'
services:
  web:
    build: .
    depends_on:
        - db
    ports:
      - "8080:8080"
  db:
    image: "mongo"
    ports:
        - 27017:27017
  compass:
    image: "mongo-express"
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - 8081:8081

